### ISSUE TITLE
Typo in rules_mapper_holdings.py causing holdings creation error

### ISSUE THREAD

**Issue by AndrewIsh** [FOLIO-FSE/MARC21-To-FOLIO#32]
Running a holdings creation I was experiencing the problem:
```
  File "/home/andrew/folio/MARC21-To-FOLIO/marc_to_folio/rules_mapper_holdings.py", line 84, in perform_additional_mapping
    folio_holding["holdingsTypeId"] = self.folio.default_holdings_type_id
AttributeError: 'FolioClient' object has no attribute 'default_holdings_type_id'
```
It looks like [line 84](https://github.com/FOLIO-FSE/MARC21-To-FOLIO/blob/honeysuckle/marc_to_folio/rules_mapper_holdings.py#L84) should actually be:
`folio_holding["holdingsTypeId"] = self.conditions.default_holdings_type_id`

**Comment by fontanka16** [comment]
Merged!
