### ISSUE TITLE
Implement Vendor mapping for Orders - Step 1

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/MARC21-To-FOLIO#516]
- [x] Assume vendor codes in FOLIO are the same as in the Order data.
- [x] Fetch all organizations (that are Vendors) from FOLIO and match by code.
- [ ] Report vendors not matching by code and assign a the orders a fallback Vendor

**Comment by branchedelac** [comment]
Fetching all organizations may be unnecessarily time-consuming for libraries with many organizations, but where not all organizations are associated with orders.

Perhaps it would be preferable to instead fetch organizations only if they are encountered in the legacy data, with a CQL query to search by code. In most cases this will mean more API calls to FOLIO, but they will be distributed across the process so should not cause too much load. Any organization that has already been fetched can also be cached and reused in case it is referenced in ore orders.

Compare with how users are fetched and cached in the feefine mapper:
https://github.com/FOLIO-FSE/folio_migration_tools/blob/ef76b4bdbd3814adb755cfafef0e8ca87fc3af36/src/folio_migration_tools/mapping_file_transformation/manual_fee_fines_mapper.py#LL236C9-L236C28

**Comment by bltravis** [comment]
Closing this. Will create a new issue for fallback if needed.
