### ISSUE TITLE
Implement FOLIO Boundwith mechanism for III libraries (Sierra & Millennium)

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/MARC21-To-FOLIO#62]
![image](https://user-images.githubusercontent.com/1894384/146789718-f6140bbf-1782-424d-81c4-195f3fc919d3.png)

**Comment by branchedelac** [comment]
Boundwith API documentation: https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/bound-with-part.html

This will be necessary for Sierra/Millennium libraries that have items linked to multiple bibs in their catalog.

**Comment by branchedelac** [comment]
Opened https://github.com/FOLIO-FSE/MARC21-To-FOLIO/issues/98
