### ISSUE TITLE
Make sure Holdings type is mapped correctly on MFHDs

### ISSUE THREAD

**Issue by fontanka16** [FOLIO-FSE/MARC21-To-FOLIO#91]
Strategies to investigate:
1. Separate the files by type
OR
2. Get it from the header. (Leader/06)

**Comment by banerjek** [comment]
Leader strikes me the ideal way to solve this. 

Separated files work fine when libraries are transmitting summary holdings. But leader does much better when different kinds of resources are interfiled

**Comment by banerjek** [comment]
Easiest way to implement that I think make almost everyone happy is to separate files by type and have script ask which type should be mapped. 

This will probably be a more reliable way of achieving the effect libraries really want than by using the leader.

**Comment by fontanka16** [comment]
Thank you @banerjek . This would be really easy to implement as well.
